---
defaults:
  mymuzak_url: https://www.mymuzak.com
  app_id: 7CkXmBORWuu9Hu9DwYp05hqZQW81oZaOtpC7NfQTGRkwFBiBQ8YxUvGzrfzlodOM
  app_secret: NrmWCcau8Of7zY0tNLUN4nmNEFr0uaOMlMEOsELW76vusZ9A0kz41iVYx2D18bmA
development:
  mymuzak_url: http://mymuzak.dev
staging:
  mymuzak_url: https://staging.mymuzak.com
  app_id: ucDXtbYSlPnyA6EfcgJ7cL39IPGON2pExQwFsoPYLgxNtWg4KvOA6jTuG17ogfvy
  app_secret: er5VvTdgSq5zunPKtydeUeCMuX8nxUawBvFPYf9M1tfHLDKoKfXNqoRIXzFp53Na
